### ISSUE TITLE
Inaccuracy in keyframe merge window calculation

### ISSUE THREAD

**Issue by lericson** [brytsknguyen/oblam_pgo#1]
It seems `span` should be updated somewhere in the loop of this code snippet:

https://github.com/brytsknguyen/oblam_pgo/blob/2686ddad2eb380a50ad70fcc2480669eeb18193a/src/oblam_pgo.cpp#L374-L383

Notice that `fId = bId` before the loop, and `span` is their difference, so 0. Substituting 0 for `span` yields this loop

```c++
        while (0 < loop_kf_nbr)
        {
            bId = max(0, bId - 1);
            fId = min(fId + 1, currId - 1);

            if (fId == bId || fId - bId >= loop_kf_nbr)
                break;
        }
```

The loop condition will either always happen, or never happen (it is constants wrt loop body). This is probably what should be happening

```c++
        // Search for keyframes arround the previous keyframe
        int bId = prevId;
        int fId = prevId;
        while (fId - bId < look_kf_nbr || (bId == 0 && fId == currId - 1))
        {
            bId = max(0, bId - 1);
            fId = min(fId + 1, currId - 1);
        }
```

**Comment by brytsknguyen** [comment]
Hi,

The program won't proceed to that line unless you have set `prevId` with the index of a keyframe that is a vertex on the loop edge the pose graph.

https://github.com/brytsknguyen/oblam_pgo/blob/2686ddad2eb380a50ad70fcc2480669eeb18193a/src/oblam_pgo.cpp#L364-L368

You need to come up with a strategy to find this index. A suggestion is given in the instruction

https://github.com/brytsknguyen/oblam_pgo/blob/2686ddad2eb380a50ad70fcc2480669eeb18193a/src/oblam_pgo.cpp#L356-L362

Once determined, pass that id to `prevId` and set `prevKfCandidateFound` to true and the `span` snippet with look for neighbours of the prevId keyframe to build a localmap for ICP matching.

**Comment by brytsknguyen** [comment]
True,

I have added "span = fId - bId;" to the while loop.
